name: Battle
description: ${project.parent.description}
authors: [ anhcraft, chochoco4777 ]
version: ${project.version}
main: dev.anhcraft.battle.BattlePlugin
api-version: "1.13"
loadbefore: [EssentialsSpawn]
depend: [PlaceholderAPI, Vault]
softdepend: [SlimeWorldManager]
