# Configdoc: https://anhcraft.dev/cd/battle/Arena.schema.html

dm_assault:
  name: "&4&lAssault"
  mode: dm
  final_exp_formula: "a+b*30-c*10+d*5"
  final_money_formula: "a*4+b*12+d*5"
  icon:
    material: grass
    name: "<arena_name>"
    lore:
      - "&4Game Mode: &f<mode_name>"
      - "&4Players: &f<game_player_count:0>/<arena_max_players>"
  max_time: 8400
  max_players: 15
  allow_late_joins: true
  rollback:
    enabled: true
    provider: battle_region
    clear_entities: true
    worlds:
      - "assault"
    region:
      corner_1: assault -315.3998 54 -216.3871 -202 13
      corner_2: assault -388.5286 37 -303.4149 -90 90
  mode_options:
    min_players: 2
    waiting_spawn_points:
      - assault -309.37 48.00 -240.57 -270.16 5.40
      - assault -309.23 48.00 -252.58 -272.11 3.45
      - assault -307.24 48.00 -278.05 -1.06 5.10
      - assault -307.50 48.00 -289.55 -1.06 4.05
    playing_spawn_points:
      - assault -369.74 37.00 -292.70 357.30 1.35
      - assault -362.64 48.00 -216.06 256.94 8.25
      - assault -340.42 48.00 -226.12 79.79 -1.65
      - assault -340.60 43.00 -247.49 357.89 4.80
      - assault -333.14 48.00 -221.80 168.89 3.00
      - assault -367.03 40.00 -265.06 270.14 6.00
      - assault -375.22 40.50 -236.96 179.54 1.35
      - assault -319.64 47.50 -285.61 357.29 3.45
    countdown_time: 300
    item_selection_time: 400
    spawn_protection_time: 40
    respawn_waiting_time: 200
    sounds:
      countdown: "$block_fence_gate_open"
  end_commands:
    winners:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%battle_game_stats_kills%+1)/(%battle_game_stats_deaths%+1) ?>"
    losers:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%battle_game_stats_kills%+1)/(%battle_game_stats_deaths%+1) ?>"
  render_gui_on_death: true
  end_firework:
    power: 3
    effects:
      '1':
        type: ball_large
        trail: true
        primary_colors:
          - red
          - green
          - yellow
        fade_colors:
          - teal
          - purple
          - aqua
          - fuchsia
      '2':
        type: burst
        primary_colors:
          - lime
          - yellow
          - aqua
          - orange
  end_delay: 60
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"

bw_lighthouse:
  name: "&e&lLighthouse"
  mode: bw
  max_time: 72000
  max_players: 16
  icon:
    material: grass
    name: "<arena_name>"
    lore:
      - "&4Game Mode: &f<mode_name>"
      - "&bPlayers: &f<game_player_count:0>/<arena_max_players>"
  final_exp_formula: "a*3+b*20-c*7.7+d*15.75"
  final_money_formula: "a*3.5+b*15-c*2.5+d*14.25"
  rollback:
    enabled: true
    provider: battle_region
    clear_entities: true
    worlds:
      - "lighthouse"
    region:
      corner_1: lighthouse 99 45 96 0 0
      corner_2: lighthouse -92 143 -95 0 0
  end_firework:
    power: 4
    effects:
      '1':
        type: ball_large
        primary_colors:
          - red
          - green
          - yellow
        fade_colors:
          - teal
          - purple
          - aqua
  end_delay: 100
  mode_options:
    min_players: 3
    countdown_time: 300
    waiting_spawn_points:
      - lighthouse 3.35 127 -3.43 -2.10 3.60
      - lighthouse -0.43 127 0.52 -91.95 2.25
      - lighthouse 3.44 127 4.45 -179.40 2.85
      - lighthouse 6.79 127 0.35 -271.35 2.70
    respawn_waiting_time: 300
    spawn_protection_time: 60
    sounds:
      countdown: "$block_fence_gate_open"
    team_size: 2
    teams:
      '1':
        name: "&fWhite"
        color: white
        spawn_points:
          - lighthouse 30.39 65 -88.76 -0.45 -1.05
          - lighthouse 27.80 65 -88.75 -0.45 -1.05
          - lighthouse 29.36 65 -88.07 -0.45 -1.05
        bed_location: lighthouse 29.53 66.56 -74.76 0 0
      '2':
        name: "&bCyan"
        color: cyan
        spawn_points:
          - lighthouse -20.62 65 -88.37 -359.85 -0.30
          - lighthouse -22.97 65 -88.38 -359.85 -0.30
          - lighthouse -21.98 65 -87.81 -357.75 -0.60
        bed_location: lighthouse -22.44 66.56 -76.01 0 0
      '3':
        name: "&eYellow"
        color: yellow
        spawn_points:
          - lighthouse -84.87 65 -26.37 -85.80 -3.30
          - lighthouse -85.03 65 -24.21 -93 -1.05
          - lighthouse -84.43 65 -25.50 -88.95 -2.70
        bed_location: lighthouse -71.96 66.56 -25.58 0 0
      '4':
        name: "&aLime"
        color: lime
        spawn_points:
          - lighthouse -85.88 65 26.93 -89.85 6.30
          - lighthouse -85.88 65 24.35 -89.85 6.30
          - lighthouse -85.42 65 25.89 -89.40 -3.15
        bed_location: lighthouse -71.94 66.56 26.50 0 0
      '5':
        name: "&1Blue"
        color: blue
        spawn_points:
          - lighthouse -23.21 65 89.21 -175.65 -0.45
          - lighthouse -21.11 65 89.18 -184.05 -1.20
          - lighthouse -22.58 65 88.23 -179.25 -0.60
        bed_location: lighthouse -22.55 66.56 76.02 0 0
      '6':
        name: "&cRed"
        color: red
        spawn_points:
          - lighthouse 30.28 65 88.80 -181.35 -2.55
          - lighthouse 28.65 65 89.59 -178.95 -2.25
          - lighthouse 26.95 65 89.26 -167.10 -1.20
        bed_location: lighthouse 29.50 66.56 76.25 0 0
      '7':
        name: "&7Gray"
        color: gray
        spawn_points:
          - lighthouse 92.52 65 23.56 -271.20 -0.90
          - lighthouse 93.10 65 26.30 -271.20 -0.90
          - lighthouse 92.48 65 28.64 -255.60 -0.75
        bed_location: lighthouse 79.16 66.56 26.43 0 0
      '8':
        name: "&dPink"
        color: pink
        spawn_points:
          - lighthouse 91.98 65 -23.18 -263.25 -1.35
          - lighthouse 92.67 65 -27.31 -277.20 -0.30
          - lighthouse 92.03 65 -25.16 -269.55 -0.75
        bed_location: lighthouse 79.12 66.56 -25.70 0 0
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"

dm_italy:
  name: "&b&lItaly"
  mode: dm
  final_exp_formula: "a+b*30-c*10+d*5"
  final_money_formula: "a*4+b*12+d*5"
  icon:
    material: GRASS
    name: "<arena_name>"
    lore:
      - "&4Game Mode: &f<mode_name>"
      - "&4Players: &f<game_current_time:0>/<arena_max_players>"
  max_time: 8400
  max_players: 20
  allow_late_joins: true
  rollback:
    enabled: true
    provider: battle_region
    region:
      corner_1: "italy -346 31 3 -96 33"
      corner_2: "italy -195 98 117 -268 10"
    clear_entities: true
    worlds:
      - "italy"
  mode_options:
    min_players: 1
    waiting_spawn_points:
      - italy -269 51 39 -90 1
      - italy -269 51 41 -90 1
      - italy -269 51 44 -90 1
      - italy -269 51 47 -90 1
    playing_spawn_points:
      - italy -305 42 84 -93.7459 3.150032
      - italy -277 42 82 -269.69574 -0.14996877
      - italy -285 42 54 -267.44608 0.7500529
      - italy -253 42 31 -271.64615 2.5500715
      - italy -272 47 50 -90.89651 4.050111
      - italy -222 46 86 -359.84628 3.9000845
      - italy -250 42 54 -88.34592 2.2500813
      - italy -323 39 44 -87.44594 2.2501101
    countdown_time: 300
    item_selection_time: 1000
    spawn_protection_time: 40
    respawn_waiting_time: 200
    sounds:
      countdown: "$block_fence_gate_open"
  render_gui_on_death: true
  end_firework:
    power: 3
    effects:
      '1':
        type: ball_large
        trail: true
        primary_colors:
          - red
          - green
          - yellow
        fade_colors:
          - teal
          - purple
          - aqua
          - fuchsia
      '2':
        type: burst
        primary_colors:
          - lime
          - yellow
          - aqua
          - orange
  end_delay: 100
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"

mr_farm:
  name: "&6&lFarm"
  mode: mr
  max_time: 18000
  max_players: 10
  icon:
    material: grass
    name: "<arena_name>"
    lore:
      - "&4Game Mode: &f<mode_name>"
      - "&bPlayers: &f<game_player_count:0>/<arena_max_players>"
  final_exp_formula: "a*4+b*18-c*7.5+d*18"
  final_money_formula: "a*4+b*15-c*3+d*20"
  rollback:
    enabled: true
    provider: battle_region
    worlds:
      - "farm"
    region:
      corner_1: "farm -121 50.0 61 -115 -1"
      corner_2: "farm 119.5 96.0 -117.5 1 74"
    clear_entities: true
  end_delay: 100
  mode_options:
    min_players: 2
    countdown_time: 300
    extra_farmer_countdown_time: 900
    waiting_spawn_points:
      - farm 70.6692 72.0 -80.1981 -180.30035 4.649932
      - farm 72.6050 72.0 -80.2021 -180.30035 4.649932
      - farm 72.6041 72.0 -82.1380 -180.30035 4.649932
      - farm 70.0207 72.0 -82.1356 -180.30035 4.649932
      - farm 71.7258 72.0 -85.1463 -180.30035 4.649932
    respawn_waiting_time: 300
    spawn_protection_time: 100
    item_selection_time: 300
    playing_spawn_points_farmer:
      - farm 44.0767 72.0 -55.6723 -88.80261 6.5999303
      - farm 43.7786 67.0 -55.0568 -359.40295 1.7999194
      - farm 46.1403 67.0 -52.0235 -90.3042 6.8999195
      - farm 48.4205 67.0 -54.9111 -359.55432 5.699922
      - farm 37.0319 67.0 -64.6029 -180.15479 9.299963
    playing_spawn_points_thief:
      - farm -92.6053 69.0 -9.7805 -182.55615 1.2000034
      - farm -89.8089 69.0 -9.8372 -182.55615 1.2000034
      - farm -86.1126 69.0 -7.13499 -157.65686 5.7000356
      - farm -90.2418 69.0 -19.8053 -85.506226 2.700028
      - farm -95.8993 69.0 -15.6838 -88.355225 2.700038
    mob_groups:
      '0':
        location: "farm 15.6338 65.0 -59.4813 -95.411865 3.89998"
        entity_type: horse
        weight: 800
        stealable: false
        amount: 1
      '1':
        location: "farm 15.6295 65.0 -55.3090 -91.36191 2.8499768"
        entity_type: horse
        weight: 800
        stealable: false
        amount: 1
      '2':
        location: "farm 15.3668 65.0 -51.2762 -93.31171 1.4999669"
        entity_type: horse
        weight: 800
        stealable: false
        amount: 1
      '3':
        location: "farm 66.0071 72.0 -83.4858 -180.01172 -1.5000186"
        entity_type: cow
        weight: 600
        stealable: true
        amount: 1
      '4':
        location: "farm 71.6872 72.0 -82.5225 -180.01123 1.7999761"
        entity_type: cow
        weight: 700
        stealable: true
        amount: 1
      '5':
        location: "farm 77.9929 72.0 -82.4463 -181.8114 0.8999981"
        entity_type: pig
        weight: 300
        stealable: true
        amount: 3
      '6':
        location: "farm 70.9739 72.0 -94.8057 -2.4117432 2.1000266"
        entity_type: pig
        weight: 400
        stealable: true
        amount: 2
      '7':
        location: "farm 66.3540 72.0 -95.0543 -1.66156 2.85002"
        entity_type: pig
        weight: 230
        stealable: true
        amount: 3
      '8':
        location: "farm 89.0294 72.0 -84.3773 -268.6612 3.600062"
        entity_type: cow
        weight: 650
        stealable: true
        amount: 2
    objectives:
      cow:
        amount:
          min: 1
          max: 2
        reward_coins: 50
      pig:
        amount:
          min: 2
          max: 5
        reward_coins: 10
    weight_speed_ratio: 5000
    gathering_region:
      corner_1: "farm -94 72 -7 0 0"
      corner_2: "farm -91 70 -2 0 0"
    sounds:
      on_pick_up_mob: "$entity_item_pickup"
      on_put_down_mob: "$block_anvil_place"
      countdown: "$block_fence_gate_open"
      extra_countdown: "$block_fence_gate_open"
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+$<money>"
      - "&b         • Exp: &e+<exp>"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
