# This configuration is a part of BattleGames

# You'll configure modes here
dm: # <-- This mode's id (do not change)
  # The mode's name
  # [required]
  name: "&bDeathmatch"

  # You can write a short sentence to describe this mode
  # [required]
  description: "&fA game where single players attack each other to know who is the winner"

  # Chat for waiting phase
  waiting_chat:
    # Should we enable it?
    enabled: true

    # The format
    # [optional] [default: <empty>] [placeholder supported]
    format: "&8%player_displayname%&f: <message>"

  # Chat for playing phase
  playing_chat:
    # Should we enable it?
    enabled: true

    # The format
    # [optional] [default: <empty>] [placeholder supported]
    format: "&8%player_displayname%&f: <message>"

  # A built-in scoreboard which is used during the waiting phase
  waiting_scoreboard:
    # Use this or not?
    enabled: true

    # This scoreboard's title
    # [optional] [default: <empty>] [placeholder supported]
    title: "&a &c&lBATTLE"

    # The content of this scoreboard
    # [optional] [placeholder supported] [maximum lines: 15]
    content:
      - "&e"
      - "&aDeathmatch - %battle_arena_name%"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"

    # The fixed length of this scoreboard
    # Set to 0 if you wanna disabling this option
    # Maximum length for a scoreboard is:
    # - 128 characters (1.13+)
    # - 32 characters (1.12)
    # [optional] [default: 0]
    fixed_length: 0

  # A built-in scoreboard which is used during the playing phase
  playing_scoreboard:
    # Use this or not?
    enabled: true

    # The title
    # [optional] [default: <empty>] [placeholder supported]
    title: "&a &c&lBATTLE"

    # The content
    # [optional] [placeholder supported] [maximum lines: 15]
    content:
      - "&e"
      - "&aDeathmatch - %battle_arena_name%"
      - "&c%battle_game_remaining_time_formatted% left"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_headshot% &aHS/AS:&r &b%battle_game_stats_headshots%/%battle_game_stats_assists%"
      - "%battle_icon_gun% &aK/D:&r &b%battle_game_stats_kills%/%battle_game_stats_deaths%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"

    # The fixed length of this scoreboard
    # Set to 0 if you wanna disabling this option
    # Maximum length for a scoreboard is:
    # - 128 characters (1.13+)
    # - 32 characters (1.12)
    # [optional] [default: 0]
    fixed_length: 0

tdm:
  name: "&eTeam &bDeathmatch"
  description: "&fA game where two teams attack each other to know who is the winner"
  waiting_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  playing_chat:
    enabled: true
    format: "&7[%battle_tdm_team%] &8%player_displayname%&f: <message>"
  waiting_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&e"
      - "&aTeam Deathmatch - %battle_arena_name%"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"
  playing_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&e"
      - "&aTeam Deathmatch - %battle_arena_name%"
      - "&c%battle_game_remaining_time_formatted% left"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_letter% &aTeam: &f%battle_tdm_team% &e(%battle_tdm_team_players% players)"
      - "%battle_icon_headshot% &aHS/AS:&r &b%battle_game_stats_headshots%/%battle_game_stats_assists%"
      - "%battle_icon_gun% &aK/D:&r &b%battle_game_stats_kills%/%battle_game_stats_deaths%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"

ctf:
  name: "&cCapture &fthe &eflag"
  description: "&fA game where two teams capture as many flags as possible to become the winner"
  waiting_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  playing_chat:
    enabled: true
    format: "&7[%battle_ctf_team%] &8%player_displayname%&f: <message>"
  waiting_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&f"
      - "&cCTF - %battle_arena_name%"
      - "&d"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32
  playing_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&f"
      - "&cCTF - %battle_arena_name%"
      - "&c%battle_game_remaining_time_formatted% left"
      - "&d"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_letter% &aTeam: &f%battle_ctf_team% &e(%battle_ctf_team_players% players)"
      - "%battle_icon_medal% &aFlags: &f%battle_ctf_team_valid_flags%/%battle_ctf_team_all_flags%/%battle_ctf_flags%"
      - "%battle_icon_headshot% &aHS/AS:&r &b%battle_game_stats_headshots%/%battle_game_stats_assists%"
      - "%battle_icon_gun% &aK/D:&r &b%battle_game_stats_kills%/%battle_game_stats_deaths%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32

bw:
  name: "&eBedWars"
  description: "&fA game where you (and your teammates) have to protect your bed against enemies and kill them to obtain the victory"
  waiting_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  playing_chat:
    enabled: true
    format: "&7[%battle_bw_team%] &8%player_displayname%&f: <message>"
  waiting_scoreboard:
    enabled: true
    title: "&a &e&lBATTLE"
    content:
      - "&f"
      - "&bBedWars - %battle_arena_name%"
      - "&d"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32
  playing_scoreboard:
    enabled: true
    title: "&a &e&lBATTLE"
    content:
      - "&f"
      - "&bBedWars - %battle_arena_name%"
      - "&d%battle_game_remaining_time_formatted% left"
      - "&d"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_letter% &aTeam: &f%battle_bw_team% &e(%battle_bw_team_players%/%battle_bw_max_team_players%)"
      - "%battle_icon_gun% &aK/D:&r &b%battle_game_stats_kills%/%battle_game_stats_deaths%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32
