# Configdoc: https://anhcraft.dev/cd/battle/Mode.schema.html

dm:
  name: "&bDeathmatch"
  waiting_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  playing_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  waiting_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&e"
      - "&aDeathmatch - %battle_arena_name%"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"
    fixed_length: 0
  playing_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&e"
      - "&aDeathmatch - %battle_arena_name%"
      - "&c%battle_game_remaining_time_formatted% left"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_headshot% &aHS/AS:&r &b%battle_game_stats_headshots%/%battle_game_stats_assists%"
      - "%battle_icon_gun% &aK/D:&r &b%battle_game_stats_kills%/%battle_game_stats_deaths%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"
    fixed_length: 0

tdm:
  name: "&eTeam &bDeathmatch"
  waiting_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  playing_chat:
    enabled: true
    format: "&7[%battle_tdm_team%] &8%player_displayname%&f: <message>"
  waiting_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&e"
      - "&aTeam Deathmatch - %battle_arena_name%"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"
  playing_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&e"
      - "&aTeam Deathmatch - %battle_arena_name%"
      - "&c%battle_game_remaining_time_formatted% left"
      - "&b"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_letter% &aTeam: &f%battle_tdm_team% &e(%battle_tdm_team_players% players)"
      - "%battle_icon_headshot% &aHS/AS:&r &b%battle_game_stats_headshots%/%battle_game_stats_assists%"
      - "%battle_icon_gun% &aK/D:&r &b%battle_game_stats_kills%/%battle_game_stats_deaths%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&c"
      - "&dminecraft.net"

ctf:
  name: "&cCapture &fthe &eflag"
  waiting_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  playing_chat:
    enabled: true
    format: "&7[%battle_ctf_team%] &8%player_displayname%&f: <message>"
  waiting_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&f"
      - "&cCTF - %battle_arena_name%"
      - "&d"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32
  playing_scoreboard:
    enabled: true
    title: "&a &c&lBATTLE"
    content:
      - "&f"
      - "&cCTF - %battle_arena_name%"
      - "&c%battle_game_remaining_time_formatted% left"
      - "&d"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_letter% &aTeam: &f%battle_ctf_team% &e(%battle_ctf_team_players% players)"
      - "%battle_icon_medal% &aFlags: &f%battle_ctf_team_valid_flags%/%battle_ctf_team_all_flags%/%battle_ctf_flags%"
      - "%battle_icon_headshot% &aHS/AS:&r &b%battle_game_stats_headshots%/%battle_game_stats_assists%"
      - "%battle_icon_gun% &aK/D:&r &b%battle_game_stats_kills%/%battle_game_stats_deaths%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32

bw:
  name: "&eBedWars"
  waiting_chat:
    enabled: true
    format: "&8%player_displayname%&f: <message>"
  playing_chat:
    enabled: true
    format: "&7[%battle_bw_team%] &8%player_displayname%&f: <message>"
  waiting_scoreboard:
    enabled: true
    title: "&a &e&lBATTLE"
    content:
      - "&f"
      - "&bBedWars - %battle_arena_name%"
      - "&d"
      - "%battle_icon_money_bag% &a%battle_ig_eco_currency%: &f%battle_ig_eco_balance%"
      - "%battle_icon_user% &aOnline: &f%battle_game_total_players%/%battle_arena_max_players%"
      - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32
  playing_scoreboard:
    enabled: true
    title: "&a &e&lBATTLE"
    content:
      - "&f"
      - "&d%battle_game_remaining_time_formatted% left"
      - "&e%battle_ig_eco_balance%"
      - "&d"
      - "&c&lR &r&fRed: %battle_bw_bed_status_red% &b(%battle_bw_team_red_players%)"
      - "&1&lB &r&fBlue: %battle_bw_bed_status_blue% &b(%battle_bw_team_blue_players%)"
      - "&a&lG &r&fGreen: %battle_bw_bed_status_lime% &b(%battle_bw_team_lime_players%)"
      - "&e&lY &r&fYellow: %battle_bw_bed_status_yellow% &b(%battle_bw_team_yellow_players%)"
      - "&b&lA &r&fAqua: %battle_bw_bed_status_cyan% &b(%battle_bw_team_cyan_players%)"
      - "&f&lW &r&fWhite: %battle_bw_bed_status_white% &b(%battle_bw_team_white_players%)"
      - "&d&lP &r&fPink: %battle_bw_bed_status_pink% &b(%battle_bw_team_pink_players%)"
      - "&7&lG &r&fGray: %battle_bw_bed_status_gray% &b(%battle_bw_team_gray_players%)"
      - "&e"
      - "&eminecraft.net"
    fixed_length: 32
