# This configuration is a part of ABM

# Use this configuration to set up your arenas
# Lets start with the first one

dm_demo: # The id of this arena
  # This is the name of this arena
  # [required]
  name: "&aExample Arena 1"

  # The mode of this arena
  # [required] [case-insensitive]
  mode: deathmatch

  # The formula which is used to calculate the final experience
  # that players receive when finishing the game.
  # Read the documentation for further information.
  # [required] [expression supported]
  final_exp_formula: "a+b*30-c*10+d*5"

  # The formula which is used to calculate the final money that players
  # receive when finishing the game.
  # Read the documentation for further information.
  # [required] [expression supported]
  final_money_formula: "a*4+b*12+d*5"

  # Arenas icon.
  # This section uses ABIF which you can look at here to know
  # the format: https://github.com/anhcraft/ABIF/blob/master/README.md
  # [required] [placeholder supported]
  icon:
    material: GRASS
    name: "{__arena_name__}"
    lore:
      - "&4Mode: &f{__mode_name__}"
      - "&4Players: &f{__game_current_time:0__}/{__arena_max_players__}"

  # Maximum playing time
  # [optional] [default: 0] [time unit: ticks]
  max_time: 8400

  # The maximum amount of players
  # [optional] [default: 0]
  max_players: 15

  # Arenas attributes configuration
  # Attributes depend on the mode, so make sure you have
  # read the documentation to fill this section completely.
  # And don't copy/paste as options should be UNIQUE for EACH arena.
  attr:
    min_players: 2
    waiting_spawn_points:
      - dm_assault 0 0 0
    playing_spawn_points:
      - dm_assault 0 0 0 0 0
    countdown_time: 300
    item_selection_time: 200
    spawn_protection_time: 40
    respawn_waiting_time: 200

  # Commands to be executed by the console at the end
  # You can use expressions within commands.
  # The format is: <? your expression ?> (e.g: <? 5^3+2 ?>)
  # Placeholders inside expressions are allowed.
  # Make sure returning values are numbers!!!
  # [expression supported] [placeholder supported]
  end_commands:
    # For winners.
    # [optional]
    winners:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%abm_game_stats_kills%+1)/(%abm_game_stats_deaths%+1) ?>"

    # For losers.
    # [optional]
    losers:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%abm_game_stats_kills%+1)/(%abm_game_stats_deaths%+1) ?>"

  # When a player dies, should we re-render his bottom gui?
  # This option can prevent players from using previous Battle items
  render_gui_on_death: true

tdm_demo:
  name: "&aExample Arena 2"
  mode: team_deathmatch
  max_time: 8400
  max_players: 10
  icon:
    material: diamond_sword
    name: "{__arena_name__}"
    lore:
      - "&eMode: &f{__mode_name__}"
      - "&ePlayers: &f{__game_current_time:0__}/{__arena_max_players__}"
    enchant:
      sharpness: 1
    flag:
      - hide_enchants
    unbreakable: true
  final_exp_formula: "a*2+b*28-c*8+d*3"
  final_money_formula: "a*5+b*15+d*3"
  attr:
    min_players: 2
    waiting_spawn_points:
      - dm_assault 0 0 0
    playing_spawn_points_a:
      - dm_assault 0 0 0
    playing_spawn_points_b:
      - dm_assault 0 0 0
    countdown_time: 300
    item_selection_time: 200
    spawn_protection_time: 40
    respawn_waiting_time: 200
  render_inv_on_death: true
