# This configuration is a part of BattleGames
# https://anhcraft.dev/cd/battle/Arena.html

dm_demo:
  name: "&aDEATHMATCH"
  mode: dm
  final_exp_formula: "a+b*30-c*10+d*5"
  final_money_formula: "a*4+b*12+d*5"
  icon:
    material: GRASS
    name: "{__arena_name__}"
    lore:
      - "&4Mode: &f{__mode_name__}"
      - "&4Players: &f{__game_current_time:0__}/{__arena_max_players__}"
  max_time: 8400
  max_players: 15
  allow_late_joins: true
  attr:
    min_players: 2
    waiting_spawn_points:
      - assault -309.37 48.00 -240.57 -270.16 5.40
      - assault -309.23 48.00 -252.58 -272.11 3.45
      - assault -307.24 48.00 -278.05 -1.06 5.10
      - assault -307.50 48.00 -289.55 -1.06 4.05
    playing_spawn_points:
      - assault -369.74 37.00 -292.70 357.30 1.35
      - assault -362.64 48.00 -216.06 256.94 8.25
      - assault -340.42 48.00 -226.12 79.79 -1.65
      - assault -340.60 43.00 -247.49 357.89 4.80
      - assault -333.14 48.00 -221.80 168.89 3.00
      - assault -367.03 40.00 -265.06 270.14 6.00
      - assault -375.22 40.50 -236.96 179.54 1.35
      - assault -319.64 47.50 -285.61 357.29 3.45
    countdown_time: 300
    item_selection_time: 200
    spawn_protection_time: 40
    respawn_waiting_time: 200
  end_commands:
    winners:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%battle_game_stats_kills%+1)/(%battle_game_stats_deaths%+1) ?>"
    losers:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%battle_game_stats_kills%+1)/(%battle_game_stats_deaths%+1) ?>"
  render_gui_on_death: true
  end_firework:
    power: 3
    effects:
      '1':
        type: ball_large
        trail: true
        primary_colors:
          - red
          - green
          - yellow
        fade_colors:
          - teal
          - purple
          - aqua
          - fuchsia
      '2':
        type: burst
        primary_colors:
          - lime
          - yellow
          - aqua
          - orange
  end_delay: 60
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"

tdm_demo:
  name: "&aTEAM DEATHMATCH"
  mode: tdm
  max_time: 8400
  max_players: 10
  icon:
    material: diamond_sword
    name: "{__arena_name__}"
    lore:
      - "&eMode: &f{__mode_name__}"
      - "&ePlayers: &f{__game_current_time:0__}/{__arena_max_players__}"
    enchant:
      sharpness: 1
    flag:
      - hide_enchants
    unbreakable: true
  final_exp_formula: "a*2+b*28-c*8+d*3"
  final_money_formula: "a*5+b*15+d*3"
  attr:
    min_players: 2
    waiting_spawn_points:
      - assault -309.37 48.00 -240.57 -270.16 5.40
      - assault -309.23 48.00 -252.58 -272.11 3.45
      - assault -307.24 48.00 -278.05 -1.06 5.10
      - assault -307.50 48.00 -289.55 -1.06 4.05
    playing_spawn_points_a:
      - assault -369.74 37.00 -292.70 357.30 1.35
      - assault -362.64 48.00 -216.06 256.94 8.25
      - assault -340.42 48.00 -226.12 79.79 -1.65
      - assault -340.60 43.00 -247.49 357.89 4.80
      - assault -333.14 48.00 -221.80 168.89 3.00
      - assault -367.03 40.00 -265.06 270.14 6.00
      - assault -375.22 40.50 -236.96 179.54 1.35
      - assault -319.64 47.50 -285.61 357.29 3.45
    playing_spawn_points_b:
      - assault -369.74 37.00 -292.70 357.30 1.35
      - assault -362.64 48.00 -216.06 256.94 8.25
      - assault -340.42 48.00 -226.12 79.79 -1.65
      - assault -340.60 43.00 -247.49 357.89 4.80
      - assault -333.14 48.00 -221.80 168.89 3.00
      - assault -367.03 40.00 -265.06 270.14 6.00
      - assault -375.22 40.50 -236.96 179.54 1.35
      - assault -319.64 47.50 -285.61 357.29 3.45
    countdown_time: 300
    item_selection_time: 200
    spawn_protection_time: 40
    respawn_waiting_time: 200
  end_delay: 60
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"

ctf_demo:
  name: "&aCTF [REMOTE]"
  mode: ctf
  bungeecord:
    enabled: true
    remote_servers:
      - "server1"
      - "server2"
  max_time: 12000
  max_players: 8
  icon:
    material: grass
    name: "{__arena_name__}"
    lore:
      - "&eMode: &f{__mode_name__}"
      - "&ePlayers: &f{__game_current_time:0__}/{__arena_max_players__}"
  final_exp_formula: "a*3+b*25-c*8+d*5.7"
  final_money_formula: "a*4.5+b*18+d*3"
  attr:
    min_players: 2
    waiting_spawn_points:
      - assault -309.37 48.00 -240.57 -270.16 5.40
      - assault -309.23 48.00 -252.58 -272.11 3.45
      - assault -307.24 48.00 -278.05 -1.06 5.10
      - assault -307.50 48.00 -289.55 -1.06 4.05
    playing_spawn_points_a:
      - assault -369.74 37.00 -292.70 357.30 1.35
      - assault -362.64 48.00 -216.06 256.94 8.25
      - assault -340.42 48.00 -226.12 79.79 -1.65
      - assault -340.60 43.00 -247.49 357.89 4.80
      - assault -333.14 48.00 -221.80 168.89 3.00
      - assault -367.03 40.00 -265.06 270.14 6.00
      - assault -375.22 40.50 -236.96 179.54 1.35
      - assault -319.64 47.50 -285.61 357.29 3.45
    playing_spawn_points_b:
      - assault -369.74 37.00 -292.70 357.30 1.35
      - assault -362.64 48.00 -216.06 256.94 8.25
      - assault -340.42 48.00 -226.12 79.79 -1.65
      - assault -340.60 43.00 -247.49 357.89 4.80
      - assault -333.14 48.00 -221.80 168.89 3.00
      - assault -367.03 40.00 -265.06 270.14 6.00
      - assault -375.22 40.50 -236.96 179.54 1.35
      - assault -319.64 47.50 -285.61 357.29 3.45
    countdown_time: 300
    item_selection_time: 180
    spawn_protection_time: 60
    respawn_waiting_time: 200
    flags:
      '1':
        location: assault -345.41 43.00 -224.30 52.35 11.55
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 10
        start_capture_sound: "$entity_player_levelup"
        stop_capture_sound: "$ui_toast_challenge_complete"
      '2':
        location: assault -355.86 40.50 -285.70 176.70 90.00
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 15
      '3':
        location: assault -385.20 40.50 -262.56 201.00 88.80
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 12
      '4':
        location: assault -368.37 41.00 -247.33 281.70 10.95
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 15
  end_delay: 80
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"

bw_demo:
  name: "&aBEDWAR"
  mode: bw
  max_time: 72000
  max_players: 16
  icon:
    material: grass
    name: "{__arena_name__}"
    lore:
      - "&bMode: &f{__mode_name__}"
      - "&bPlayers: &f{__game_current_time:0__}/{__arena_max_players__}"
  final_exp_formula: "a*3+b*20-c*7.7+d*15.75"
  final_money_formula: "a*3.5+b*15-c*2.5+d*14.25"
  rollback:
    enabled: true
    provider: SLIME_WORLD
    worlds:
      - lighthouse
  end_firework:
    power: 4
    effects:
      '1':
        type: ball_large
        primary_colors:
          - red
          - green
          - yellow
        fade_colors:
          - teal
          - purple
          - aqua
  end_delay: 100
  attr:
    min_players: 3
    countdown_time: 300
    waiting_spawn_points:
      - lighthouse 3.35 127 -3.43 -2.10 3.60
      - lighthouse -0.43 127 0.52 -91.95 2.25
      - lighthouse 3.44 127 4.45 -179.40 2.85
      - lighthouse 6.79 127 0.35 -271.35 2.70
    respawn_waiting_time: 300
    spawn_protection_time: 60
    team_size: 2
    teams:
      '1':
        name: "&fWhite"
        color: white
        spawn_points:
          - lighthouse 30.39 65 -88.76 -0.45 -1.05
          - lighthouse 27.80 65 -88.75 -0.45 -1.05
          - lighthouse 29.36 65 -88.07 -0.45 -1.05
        bed_location: lighthouse 29.53 66.56 -74.76 0 0
      '2':
        name: "&bCyan"
        color: cyan
        spawn_points:
          - lighthouse -20.62 65 -88.37 -359.85 -0.30
          - lighthouse -22.97 65 -88.38 -359.85 -0.30
          - lighthouse -21.98 65 -87.81 -357.75 -0.60
        bed_location: lighthouse -22.44 66.56 -76.01 0 0
      '3':
        name: "&eYellow"
        color: yellow
        spawn_points:
          - lighthouse -84.87 65 -26.37 -85.80 -3.30
          - lighthouse -85.03 65 -24.21 -93 -1.05
          - lighthouse -84.43 65 -25.50 -88.95 -2.70
        bed_location: lighthouse -71.96 66.56 -25.58 0 0
      '4':
        name: "&aLime"
        color: lime
        spawn_points:
          - lighthouse -85.88 65 26.93 -89.85 6.30
          - lighthouse -85.88 65 24.35 -89.85 6.30
          - lighthouse -85.42 65 25.89 -89.40 -3.15
        bed_location: lighthouse -71.94 66.56 26.50 0 0
      '5':
        name: "&1Blue"
        color: blue
        spawn_points:
          - lighthouse -23.21 65 89.21 -175.65 -0.45
          - lighthouse -21.11 65 89.18 -184.05 -1.20
          - lighthouse -22.58 65 88.23 -179.25 -0.60
        bed_location: lighthouse -22.55 66.56 76.02 0 0
      '6':
        name: "&cRed"
        color: red
        spawn_points:
          - lighthouse 30.28 65 88.80 -181.35 -2.55
          - lighthouse 28.65 65 89.59 -178.95 -2.25
          - lighthouse 26.95 65 89.26 -167.10 -1.20
        bed_location: lighthouse 29.50 66.56 76.25 0 0
      '7':
        name: "&7Gray"
        color: gray
        spawn_points:
          - lighthouse 92.52 65 23.56 -271.20 -0.90
          - lighthouse 93.10 65 26.30 -271.20 -0.90
          - lighthouse 92.48 65 28.64 -255.60 -0.75
        bed_location: lighthouse 79.16 66.56 26.43 0 0
      '8':
        name: "&dPink"
        color: pink
        spawn_points:
          - lighthouse 91.98 65 -23.18 -263.25 -1.35
          - lighthouse 92.67 65 -27.31 -277.20 -0.30
          - lighthouse 92.03 65 -25.16 -269.55 -0.75
        bed_location: lighthouse 79.12 66.56 -25.70 0 0
  result_broadcast:
    won:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&a         Congratulations! You WON the game!         "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
    lost:
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
      - "&f"
      - "&7       You lost. Be better in the next match!       "
      - "&f"
      - "&b         • Money: &e+${__money__}"
      - "&b         • Exp: &e+{__exp__}"
      - "&f"
      - "&f+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+"
