# This configuration is a part of ABM
# https://anhcraft.dev/cd/abm/Arena.html

dm_demo:
  name: "&aExample Arena 1"
  mode: dm
  final_exp_formula: "a+b*30-c*10+d*5"
  final_money_formula: "a*4+b*12+d*5"
  icon:
    material: GRASS
    name: "{__arena_name__}"
    lore:
      - "&4Mode: &f{__mode_name__}"
      - "&4Players: &f{__game_current_time:0__}/{__arena_max_players__}"
  max_time: 8400
  max_players: 15
  attr:
    min_players: 2
    waiting_spawn_points:
      - dm_assault 0 0 0
    playing_spawn_points:
      - dm_assault 0 0 0 0 0
    countdown_time: 300
    item_selection_time: 200
    spawn_protection_time: 40
    respawn_waiting_time: 200
  end_commands:
    winners:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%abm_game_stats_kills%+1)/(%abm_game_stats_deaths%+1) ?>"
    losers:
      - "msg %player_name% &aYour last K/D ratio: &e<? (%abm_game_stats_kills%+1)/(%abm_game_stats_deaths%+1) ?>"
  render_gui_on_death: true
  end_firework:
    power: 3
    effects:
      '1':
        type: ball_large
        trail: true
        primary_colors:
          - red
          - green
          - yellow
        fade_colors:
          - teal
          - purple
          - aqua
          - fuchsia
      '2':
        type: burst
        primary_colors:
          - lime
          - yellow
          - aqua
          - orange
  end_delay: 60

tdm_demo:
  name: "&aExample Arena 2"
  mode: tdm
  max_time: 8400
  max_players: 10
  icon:
    material: diamond_sword
    name: "{__arena_name__}"
    lore:
      - "&eMode: &f{__mode_name__}"
      - "&ePlayers: &f{__game_current_time:0__}/{__arena_max_players__}"
    enchant:
      sharpness: 1
    flag:
      - hide_enchants
    unbreakable: true
  final_exp_formula: "a*2+b*28-c*8+d*3"
  final_money_formula: "a*5+b*15+d*3"
  attr:
    min_players: 2
    waiting_spawn_points:
      - dm_assault 0 0 0
    playing_spawn_points_a:
      - dm_assault 0 0 0
    playing_spawn_points_b:
      - dm_assault 0 0 0
    countdown_time: 300
    item_selection_time: 200
    spawn_protection_time: 40
    respawn_waiting_time: 200

ctf_demo:
  name: "&aExample Arena 3"
  mode: ctf
  max_time: 12000
  max_players: 8
  icon:
    material: grass
    name: "{__arena_name__}"
    lore:
      - "&eMode: &f{__mode_name__}"
      - "&ePlayers: &f{__game_current_time:0__}/{__arena_max_players__}"
  final_exp_formula: "a*3+b*25-c*8+d*5.7"
  final_money_formula: "a*4.5+b*18+d*3"
  attr:
    min_players: 2
    waiting_spawn_points:
      - ctf_italy 0 0 0
    playing_spawn_points_a:
      - ctf_italy 0 0 0
    playing_spawn_points_b:
      - ctf_italy 0 0 0
    countdown_time: 300
    item_selection_time: 180
    spawn_protection_time: 60
    respawn_waiting_time: 200
    flags:
      '1':
        location: ctf_italy 0 0 0
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 10
        start_capture_sound: "$entity_player_levelup"
        stop_capture_sound: "$ui_toast_challenge_complete"
      '2':
        location: ctf_italy 0 0 0
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 15
      '3':
        location: ctf_italy 0 0 0
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 12
      '4':
        location: ctf_italy 0 0 0
        display_name:
          valid: "&a&l{__flag_team__} | &f&l{__flag_health__} &c&l❤"
          invalid: "&7&l{__flag_team__} | &f&l{__flag_health__}/{__flag_max_health__} &c&l❤"
          neutral: "&7Neutral"
        max_health: 15

rmt_arena:
  name: "&4Example Remote Arena"
  mode: tdm
  max_time: 8400
  max_players: 16
  bungeecord:
    enabled: true
    remote_servers:
      - "server1"
      - "server2"
  icon:
    material: diamond_sword
    name: "{__arena_name__}"
    lore:
      - "&dMode &7>> &e{__mode_name__}"
      - "&dPlayers &7>> &e{__game_current_time:0__}/{__arena_max_players__}"
    enchant:
      sharpness: 1
    flag:
      - hide_enchants
  final_exp_formula: "a*2+b*28-c*8+d*3"
  final_money_formula: "a*5+b*15+d*3"
  attr:
    min_players: 2
    waiting_spawn_points:
      - dm_assault 0 0 0
    playing_spawn_points_a:
      - dm_assault 0 0 0
    playing_spawn_points_b:
      - dm_assault 0 0 0
    countdown_time: 300
    item_selection_time: 200
    spawn_protection_time: 40
    respawn_waiting_time: 200
