# This configuration is a part of BattleGames
# General plugin configuration

locale: "en_us.yml"

date_format:
  long_form: "dd/MM/yyyy HH:mm:ss"
  short_form:
    hours: "HH:mm:ss"
    minutes: "mm:ss"
    seconds: "ss"

level_system:
  exp_to_level_formula: "floor(sqrt(x/20)/2)"
  level_to_exp_formula: "floor(x*x*4*20)"

default_scoreboard:
  enabled: true
  title: "&a &c&lBATTLE"
  content:
    - "&a&f"
    - "%battle_icon_user% &aName:&r &b%player_displayname%"
    - "%battle_icon_medal% &aLevel:&r &b%battle_level% (%battle_level_progress%%)"
    - "%battle_icon_money_bag% &aMoney:&r &b$%vault_eco_balance_formatted%"
    - "%battle_icon_gold_cup% &aW/L:&r &b%battle_stats_win_matches%/%battle_stats_lose_matches%"
    - "%battle_icon_headshot% &aHS/AS:&r &b%battle_stats_headshots%/%battle_stats_assists%"
    - "%battle_icon_gun% &aK/D:&r &b%battle_stats_kills%/%battle_stats_deaths%"
    - "%battle_icon_chart% &aTPS/Ping:&r %server_tps_1_colored%&f/%player_ping%"
    - "%battle_icon_online% &aOnline:&r &b%server_online%/%server_max_players%"
    - "&c&a"
    - "&dminecraft.net"
  fixed_length: 0

default_chat:
  enabled: true
  format: "&7[%battle_icon_medal%&r%battle_level%&7] &8%player_displayname%&f: {__message__}"

storage:
  type: file
  file:
    data_path: ".battle"
  mysql:
    hostname: localhost
    port: 3306
    database: minecraft
    username: root
    password: ""
    datasource_properties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true

misc:
  anti_death_drops: true
  default_speed:
    walk: 0.2
    fly: 0.2

bungeecord:
  enabled: false
  lobby_servers:
    - "lobby_1"
    - "lobby_2"
    - "lobby_3"
  reconnect_tries_per_server: 0
  connection_delay: 100
