player_inv:
  title: '[ gui.player_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions: 1/5; 2
      item:
        name: '[ gui.player_inv.gun_name ]'
        lore:
          - '[ gui.player_inv.gun_lore ]'
        material: diamond_axe
        damage: 1
        unbreakable: true
        flag:
          - hide_attributes
          - hide_unbreakable
      functions:
        - common::cancel_event
        - common::open_top_gui { player_gun_inv }
    '2':
      positions: 2/5; 2
      item:
        name: '[ gui.player_inv.magazine_name ]'
        lore:
          - '[ gui.player_inv.magazine_lore ]'
        material: chest
      functions:
        - common::cancel_event
        - common::open_top_gui { player_magazine_inv }
    '3':
      positions: 3/5; 2
      item:
        material: arrow
        name: '[ gui.player_inv.ammo_name ]'
        lore:
          - '[ gui.player_inv.ammo_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { player_ammo_inv }
    '4':
      positions: 4/5; 2
      item:
        material: glass
        name: '[ gui.player_inv.scope_name ]'
        lore:
          - '[ gui.player_inv.scope_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { player_scope_inv }
    '5':
      positions: 5/5; 2
      item:
        material: tnt
        name: '[ gui.player_inv.grenade_name ]'
        lore:
          - '[ gui.player_inv.grenade_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { player_grenade_inv }
    '6':
      positions: 1/1; 4
      item:
        material: barrier
        name: '[ gui.common.close_name ]'
        lore:
          - '[ gui.common.close_lore ]'
      functions:
        - common::cancel_event
        - common::close_gui

player_gun_inv:
  title: '[ gui.player_gun_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 4
      pagination: player_gun
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 5
        - 8; 5
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 5
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { player_gun }
    '3':
      positions: 7; 5
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { player_gun }
    '4':
      positions: 9; 5
      item:
        material: barrier
        name: '[ gui.common.back_inv_name ]'
        lore:
          - '[ gui.common.back_inv_lore ]'
      functions:
        - common::open_top_gui { player_inv }

player_magazine_inv:
  title: '[ gui.player_magazine_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 4
      pagination: player_magazine
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 5
        - 8; 5
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 5
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { player_magazine }
    '3':
      positions: 7; 5
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { player_magazine }
    '4':
      positions: 9; 5
      item:
        material: barrier
        name: '[ gui.common.back_inv_name ]'
        lore:
          - '[ gui.common.back_inv_lore ]'
      functions:
        - common::open_top_gui { player_inv }

player_ammo_inv:
  title: '[ gui.player_ammo_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 4
      pagination: player_ammo
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 5
        - 8; 5
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 5
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { player_ammo }
    '3':
      positions: 7; 5
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { player_ammo }
    '4':
      positions: 9; 5
      item:
        material: barrier
        name: '[ gui.common.back_inv_name ]'
        lore:
          - '[ gui.common.back_inv_lore ]'
      functions:
        - common::open_top_gui { player_inv }

player_scope_inv:
  title: '[ gui.player_scope_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 4
      pagination: player_scope
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 5
        - 8; 5
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 5
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { player_scope }
    '3':
      positions: 7; 5
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { player_scope }
    '4':
      positions: 9; 5
      item:
        material: barrier
        name: '[ gui.common.back_inv_name ]'
        lore:
          - '[ gui.common.back_inv_lore ]'
      functions:
        - common::open_top_gui { player_inv }

player_grenade_inv:
  title: '[ gui.player_grenade_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 4
      pagination: player_grenade
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 5
        - 8; 5
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 5
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { player_grenade }
    '3':
      positions: 7; 5
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { player_grenade }
    '4':
      positions: 9; 5
      item:
        material: barrier
        name: '[ gui.common.back_inv_name ]'
        lore:
          - '[ gui.common.back_inv_lore ]'
      functions:
        - common::open_top_gui { player_inv }

kit_menu:
  title: '[ gui.kit_menu.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 3
      pagination: kits
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 4
        - 8; 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 4
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { kits }
    '3':
      positions: 7; 4
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { kits }
    '4':
      positions: 9; 4
      item:
        material: barrier
        name: '[ gui.common.close_name ]'
        lore:
          - '[ gui.common.close_lore ]'
      functions:
        - common::cancel_event
        - common::close_gui

booster_menu:
  title: '[ gui.booster_menu.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 3
      pagination: boosters
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 4
        - 8; 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 4
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { boosters }
    '3':
      positions: 7; 4
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { boosters }
    '4':
      positions: 9; 4
      item:
        material: barrier
        name: '[ gui.common.close_name ]'
        lore:
          - '[ gui.common.close_lore ]'
      functions:
        - common::cancel_event
        - common::close_gui

arena_chooser:
  title: '[ gui.arena_chooser.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 3
      pagination: arena_chooser
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 4
        - 8; 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 4
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { arena_chooser }
    '3':
      positions: 7; 4
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { arena_chooser }
    '4':
      positions: 9; 4
      item:
        material: barrier
        name: '[ gui.common.close_name ]'
        lore:
          - '[ gui.common.close_lore ]'
      functions:
        - common::cancel_event
        - common::close_gui

market_category_menu:
  title: '[ gui.market_category_menu.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 3
      pagination: market_category
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 4
        - 8; 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 4
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { market_category }
    '3':
      positions: 7; 4
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { market_category }
    '4':
      positions: 9; 4
      item:
        material: barrier
        name: '[ gui.common.close_name ]'
        lore:
          - '[ gui.common.close_lore ]'
      functions:
        - common::cancel_event
        - common::close_gui

market_product_menu:
  title: '[ gui.market_product_menu.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 3
      pagination: market_product
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions:
        - 1 -> 5; 4
        - 8; 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '2':
      positions: 6; 4
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { market_product }
    '3':
      positions: 7; 4
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { market_product }
    '4':
      positions: 9; 4
      item:
        material: barrier
        name: '[ gui.market_product_menu.back_name ]'
        lore:
          - '[ gui.market_product_menu.back_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { market_category_menu }

market_category_editor:
  title: '[ gui.market_category_editor.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 3
      pagination: editor_market_category
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions: 1; 4
      item:
        material: diamond
        name: '[ gui.market_category_editor.create_name ]'
        lore:
          - '[ gui.market_category_editor.create_lore ]'
      functions:
        - common::cancel_event
        - market::create_category
        - common::refresh
    '2':
      positions:
        - 2 -> 5; 4
        - 8; 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '3':
      positions: 6; 4
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { editor_market_category }
    '4':
      positions: 7; 4
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { editor_market_category }
    '5':
      positions: 9; 4
      item:
        material: barrier
        name: '[ gui.common.close_name ]'
        lore:
          - '[ gui.common.close_lore ]'
      functions:
        - common::cancel_event
        - common::close_gui

market_product_editor:
  title: '[ gui.market_product_editor.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1 -> 9; 1 -> 3
      pagination: editor_market_product
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '1':
      positions: 1; 4
      item:
        material: diamond
        name: '[ gui.market_product_editor.create_name ]'
        lore:
          - '[ gui.market_product_editor.create_lore ]'
      functions:
        - common::cancel_event
        - market::create_product
        - common::refresh
    '2':
      positions:
        - 2 -> 5; 4
        - 8; 4
      item:
        material: GRAY_STAINED_GLASS_PANE
        name: '&f'
      functions:
        - common::cancel_event
    '3':
      positions: 6; 4
      item:
        material: arrow
        name: '[ gui.common.prev_name ]'
        lore:
          - '[ gui.common.prev_lore ]'
      functions:
        - common::cancel_event
        - common::prev_page { editor_market_product }
    '4':
      positions: 7; 4
      item:
        material: arrow
        name: '[ gui.common.next_name ]'
        lore:
          - '[ gui.common.next_lore ]'
      functions:
        - common::cancel_event
        - common::next_page { editor_market_product }
    '5':
      positions: 9; 4
      item:
        material: barrier
        name: '[ gui.market_product_menu.back_name ]'
        lore:
          - '[ gui.market_product_menu.back_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { market_category_editor }

main_player_inv:
  title: '[ gui.main_player_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1; 1
      item:
        material: clock
        name: '[ gui.main_player_inv.arena_chooser_name ]'
        lore:
          - '[ gui.main_player_inv.arena_chooser_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { arena_chooser }
    '1':
      positions: 2; 1
      item:
        material: chest
        name: '[ gui.common.your_inv_name ]'
        lore:
          - '[ gui.common.your_inv_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { player_inv }

game_player_inv:
  title: '[ gui.game_player_inv.title ]'
  sound: $block_chest_open
  components:
    '0':
      positions: 1; 1
      item:
        material: chest
        name: '[ gui.common.your_inv_name ]'
        lore:
          - '[ gui.common.your_inv_lore ]'
      functions:
        - common::cancel_event
        - common::open_top_gui { player_inv }
    '1':
      positions: 9; 1
      item:
        material: barrier
        name: '[ gui.game_player_inv.quit_name ]'
        lore:
          - '[ gui.game_player_inv.quit_lore ]'
      functions:
        - common::cancel_event
        - common::quit_game
