# This configuration is a part of ABM

# You can modify guns here

ak_47: # Gun's ID
  # Put the name here
  # [required]
  name: "&e&l&nAK-47"

  # Does this gun support dual wielding?
  # [optional] [default: false]
  dual_wielding: false

  # Configure this gun's skin
  skin:
    # The primary skin
    primary:
      # The material
      # [required]
      material: diamond_axe

      # The damage
      # [optional] [default: 0]
      damage: 1

    # The secondary skin
    secondary:
      # [optional] [default: air]
      #material: air

      # [optional] [default: 0]
      #damage: 0

  # The weight of this gun
  # The value below is used to reduce the speed of its owner
  # [optional] [default: 0]
  weight: 0.0479

  # Configure this gun's magazine here
  magazine:
    # The id of the default magazine
    # [required]
    default: default_ak_47

    # The maximum magazine capacity that can attach to this gun
    # Note: The default magazine can bypass this restriction
    # [optional] [default: 0]
    max_capacity: 90

desert_eagle:
  name: "&6&l&nDesert Eagle"
  skin:
    primary:
      material: diamond_axe
      damage: 2
  weight: 0.018
  magazine:
    default: default_de
    max_capacity: 35
