# This configuration is a part of ABM

# You can configure all ammunition storage here

default_ak_47: # The id of this magazine
  # Next is its name
  # [required]
  name: "&2AK-47 Magazine"

  # Skin configuration
  skin:
    # The material
    # [optional] [default: air]
    material: chest

    # The damage
    # [optional] [default: 0]
    damage: 0

  # All ammo can be put in
  # Syntax: <ammo id>:<capacity>
  # [optional]
  ammo:
    7_62mm: 30 # it means we can have 30 rounds of 7.62mm ammo in this magazine

improved_ak_47:
  name: "&2AK-47 Magazine &5&l[Improved]"
  skin:
    material: diamond_axe
    damage: 2
  ammo:
    7_62mm: 45

default_de:
  name: "&eDE Magazine"
  skin:
    material: chest
  ammo:
    _50_ae: 7 # 7 rounds of .50 AE ammo
