speed:
  name: "&aSpeed"
  executions:
    give_effects:
      '1':
        type: speed
        duration: 99999
        particles: false

speed_plus:
  name: "&aSpeed+"
  executions:
    give_effects:
      '1':
        type: speed
        amplifier: 1
        duration: 99999
        particles: false

health_boost:
  name: "&dHealth boost"
  executions:
    set_health: 20

no_hunger:
  name: "&bNo hunger"
  executions:
    set_food_level: 20
