general:
  prevent_hungry: true
  prevent_mob_drops: true
  prevent_explosions: true
  protect_blocks: true
  always_weather: clear
  always_time: 3000
  anti_fire_spread: true
  disable_interact: true
  disable_crafting: true
  except_worlds:
    - world

specific:
  lighthouse:
    protect_blocks: false
    disable_interact: false
    prevent_mob_spawn: true

  farm:
    always_time: 18000
