# This configuration is a part of BattleGames
# https://wiki.anhcraft.dev/en/battle/ammo

7_62mm:
  name: "&f7.62mm"
  skin:
    material: arrow
    damage: 0
  bullets:
    '1':
      damage: 12
      knockback: 0.1
      penetration_power: 20
      particle:
        type: end_rod

_50_ae:
  name: "&f.50 Action Express"
  skin:
    material: arrow
  bullets:
    '1':
      damage: 10.8
      knockback: 0.102
      penetration_power: 20
      particle:
        type: end_rod

308_Winchester:
  name: "&f.308 Winchester"
  skin:
    material: arrow
  bullets:
    '1':
      damage: 25
      knockback: 0.2
      penetration_power: 50
      particle:
        type: end_rod
