fire_grenade:
  name: "&cFire &fGrenade"
  skin:
    material: shears
    damage: 1
  delay_time: 70
  velocity_multiplier: 2.5
  fire:
    mob_ticks: 100
    mob_radius: 3.5
    block_radius: 2

explosive_grenade:
  name: "&4Explosive &aGrenade"
  skin:
    material: shears
    damage: 1
  delay_time: 60
  explosion_power: 3
  velocity_multiplier: 2.7
