# This configuration is a part of BattleGames
# https://wiki.anhcraft.dev/en/battle/items

ammo:
  name: "{__ammo_name__}"
  lore:
    - "&aBullets: &f{__ammo_bullet_count__}"
    - "&e> Total damage: &f{__ammo_total_bullet_damage__}"
    - "&e> Total knockback: &f{__ammo_total_bullet_knockback__}"

model_ammo:
  name: "{__ammo_name__}"
  lore:
    - "&aBullets: &f{__ammo_bullet_count__}"
    - "&e> Total damage: &f{__ammo_total_bullet_damage__}"
    - "&e> Total knockback: &f{__ammo_total_bullet_knockback__}"

magazine:
  name: "{__magazine_name__}"
  lore:
    - "&aAmmo: &f{__magazine_ammo_count__}/{__magazine_ammo_capacity__} {__ammo_name__}"

model_magazine:
  name: "{__magazine_name__}"

gun:
  name: "{__gun_name__}"
  lore:
    - "&aAmmo: &f{__ammo_name__} &e({__magazine_ammo_count__}/{__magazine_ammo_capacity__})"
    - "&aWeight: &f{__gun_weight__}"
    - "&aMagazine: &f{__magazine_name__}"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

model_gun:
  name: "{__gun_name__}"
  lore:
    - "&aWeight: &f{__gun_weight__}"
    - "&aMagazine:"
    - "&e> Default: &f{__default_magazine_name__}"
    - "&e> Maximum capacity: &f{__gun_max_magazine_capacity__}"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

scope:
  name: "{__scope_name__}"

model_scope:
  name: "{__scope_name__}"

model_grenade:
  name: "{__grenade_name__}"
  lore:
    - "&aExplosion power: &f{__grenade_explosion_power__}"
    - "&aDelay time: &f{__grenade_delay_time__}"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

grenade:
  name: "{__grenade_name__}"
  lore:
    - "&aExplosion power: &f{__grenade_explosion_power__}"
    - "&aDelay time: &f{__grenade_delay_time__}"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true
