# This configuration is a part of BattleGames
# https://wiki.anhcraft.dev/en/battle/magazine

default_ak_47:
  name: "&2AK-47 Magazine"
  skin:
    material: chest
    damage: 0
  ammo:
    7_62mm: 30

improved_ak_47:
  name: "&2AK-47 Magazine &5&l[Improved]"
  skin:
    material: diamond_axe
    damage: 2
  ammo:
    7_62mm: 45

default_de:
  name: "&eDE Magazine"
  skin:
    material: chest
  ammo:
    _50_ae: 7
