# Wiki: https://wiki.anhcraft.dev/en/battle/scope
# Configdoc: https://anhcraft.dev/cd/battle/ScopeModel.schema.html

basic_scope:
  name: "&aBasic scope"
  skin:
    material: GLASS
    damage: 0
  zoom_levels:
    - 20
