# This configuration is a part of BattleGames
# https://wiki.anhcraft.dev/en/battle/scope

basic_scope:
  name: "&aBasic scope"
  skin:
    material: GLASS
    damage: 0
  zoom_levels:
    - 1
    - 7

enhanced_scope:
  name: "&5Enhanced scope"
  skin:
    material: GLASS
    damage: 0
  zoom_levels:
    - 3
    - 10
