# This configuration is a part of BattleGames
# https://wiki.anhcraft.dev/en/battle/grenade

fire_grenade:
  name: "&cFire &fGrenade"
  skin:
    material: shears
    damage: 1
  delay_time: 70
  velocity_multiplier: 2.5
  inventory_slot: 2
  fire:
    mob_ticks: 100
    mob_radius: 3.5
    block_radius: 2
