# This configuration is a part of BattleGames
# https://wiki.anhcraft.dev/en/battle/items

ammo:
  name: "<ammo_name>"
  lore:
    - "&aBullets: &f<ammo_bullet_count>"
    - "&e> Total damage: &f<ammo_total_bullet_damage>"
    - "&e> Total knockback: &f<ammo_total_bullet_knockback>"

model_ammo:
  name: "<ammo_name>"
  lore:
    - "&aBullets: &f<ammo_bullet_count>"
    - "&e> Total damage: &f<ammo_total_bullet_damage>"
    - "&e> Total knockback: &f<ammo_total_bullet_knockback>"

magazine:
  name: "<magazine_name>"
  lore:
    - "&aAmmo: &f<magazine_ammo_count>/<magazine_ammo_capacity> <ammo_name>"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

model_magazine:
  name: "<magazine_name>"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

gun:
  name: "<gun_name>"
  lore:
    - "&aAmmo: &f<ammo_name> &e(<magazine_ammo_count>/<magazine_ammo_capacity>)"
    - "&aWeight: &f<gun_weight>"
    - "&aMagazine: &f<magazine_name>"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

model_gun:
  name: "<gun_name>"
  lore:
    - "&aWeight: &f<gun_weight>"
    - "&aMagazine:"
    - "&e> Default: &f<default_magazine_name>"
    - "&e> Maximum capacity: &f<gun_max_magazine_capacity>"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

scope:
  name: "<scope_name>"

model_scope:
  name: "<scope_name>"

model_grenade:
  name: "<grenade_name>"
  lore:
    - "&aExplosion power: &f<grenade_explosion_power>"
    - "&aDelay time: &f<grenade_delay_time>"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true

grenade:
  name: "<grenade_name>"
  lore:
    - "&aExplosion power: &f<grenade_explosion_power>"
    - "&aDelay time: &f<grenade_delay_time>"
  flag:
    - hide_attributes
    - hide_unbreakable
  unbreakable: true
