# This configuration is a part of BattleGames
# https://wiki.anhcraft.dev/en/battle/magazine

default_ak_47:
  name: "&2AK-47 Magazine"
  skin:
    material: stone_sword
    damage: 2
  ammo:
    7_62mm: 30

improved_ak_47:
  name: "&2AK-47 Magazine &5&l[Improved]"
  skin:
    material: stone_sword
    damage: 3
  ammo:
    7_62mm: 45

default_de:
  name: "&eDE Magazine"
  skin:
    material: stone_sword
    damage: 2
  ammo:
    _50_ae: 7

default_awm:
  name: "&4AWM Magazine"
  skin:
    material: stone_sword
    damage: 3
  ammo:
    308_Winchester: 10

default_xm1014:
  name: "&eXM1014"
  skin:
    material: stone_sword
    damage: 2
  ammo:
    12_gauge: 7
