# Wiki: https://wiki.anhcraft.dev/en/battle/magazine
# Configdoc: https://anhcraft.dev/cd/battle/MagazineModel.schema.html

default_ak_47:
  name: "&2AK-47 Magazine"
  skin:
    material: stone_sword
    damage: 2
  ammo:
    7_62mm: 30

improved_ak_47:
  name: "&2AK-47 Magazine &5&l[Improved]"
  skin:
    material: stone_sword
    damage: 3
  ammo:
    7_62mm: 45

default_de:
  name: "&eDE Magazine"
  skin:
    material: stone_sword
    damage: 2
  ammo:
    _50_ae: 7

default_awm:
  name: "&4AWM Magazine"
  skin:
    material: stone_sword
    damage: 3
  ammo:
    308_Winchester: 10

default_xm1014:
  name: "&eXM1014"
  skin:
    material: stone_sword
    damage: 2
  ammo:
    12_gauge: 7

default_m4a4:
  name: "&eM4A4"
  skin:
    material: stone_sword
    damage: 1
  ammo:
    5_56_nato: 30
