# Medical kit settings
# Get it with: /minecraft:give @p minecraft:stone_sword{Damage:1, Unbreakable:1} 1
# You can put this item in the market with following settings:
# - Material type: Stone sword
# - Durability: 1
# - Unbreakable: true
medical_kit:
  # Additional health given to the player
  health_bonus: 15

# World settings
world_settings:
  # General configuration
  general:
    # Prevent hungry
    prevent_hungry: true

    # Prevent mobs from dropping items
    prevent_mob_drops: true

    # Prevent explosions
    prevent_explosions: true

    # Protect the blocks
    protect_blocks: true

    # Control the weather
    always_weather: clear

    # Control the world time
    always_time: 18000

    # Any worlds that will not get effect
    except_worlds:
      - world

  # Specific world settings
  specific:
    lighthouse: # The world's name
      # If you install the BedwarPack addon, it has a feature similar to
      # this. It is recommended to use that and disable this option.
      # If you enable, players can't place any blocks!!!
      protect_blocks: false

      prevent_hungry: false

    assault:
      always_time: 18000
