# Medical kit settings
# Get it with: /minecraft:give @p minecraft:stone_sword{Damage:1, Unbreakable:1} 1
# You can put this item in the market with following settings:
# - Material type: Stone sword
# - Durability: 1
# - Unbreakable: true
medical_kit:
  # Additional health given to the player
  health_bonus: 15

# World settings
world_settings:
  # General configuration
  general:
    # Prevent hungry
    prevent_hungry: true

    # Prevent mobs from dropping items
    prevent_mob_drops: true

    # Prevent explosions
    prevent_explosions: true

    # Protect the blocks
    protect_blocks: true

    # Control the weather
    always_weather: clear

    # Control the world time
    always_time: 3000

    # Prevent fire spread
    anti_fire_spread: true

    # Any worlds that will not get effect
    except_worlds:
      - world

  # Specific world settings
  specific:
    lighthouse: # The world's name
      # If you install the BedwarPack addon, it has a feature similar to
      # this. It is recommended to use that and disable this option.
      # If you enable, players can't place any blocks!!!
      protect_blocks: false

      prevent_hungry: false

# Extra arenas settings
arena_settings:
  bw_demo: # Write arena's id here
    # Remove all blocks in a specific region when the game starts.
    # Two locations must be in THE SAME WORLD.
    # [WARNING] Rollback system must be enabled! Otherwise your worlds will be broken forever!!!
    empty_regions:
      '1':
        corner_1: "lighthouse 23 118 -20 56 30"
        corner_2: "lighthouse -10 143 15 -138 20"

# Radio settings
radio_settings:
  format: "&6[RADIO] &8%player_displayname%&f: <message>"
